### ISSUE TITLE
how to get the value of ganglia metrics ?

### ISSUE THREAD

**Issue by kkpbbb** [logstash-plugins/logstash-input-ganglia#2]
Hi：

when I use the logstash-input-ganglia to receive package from gmond and save to elasticsearch,
I can get the metrics base info like name type unit ...，But I can't get the value of metrics 

I read the source ,and I think should modify ganglia.rb and add
event["val"] = data["val"]
before 
%w{dmax tmax slope type units}.each do |info|

am I right ?

sorry for my bad english

**Comment by hd8622** [comment]
Hi kkpbbb

I am also stuck in the same problme
Were you able to solve the issue ?

Can you share your ganglia.rb 

Thanks in advance

**Comment by milonimrod** [comment]
same problem

**Comment by hd8622** [comment]
Hi

I have resolved this problem

But currently i on vacation so do not have details with me.

If you need solution i can provide you with details next week

Regards
himanshu

**Comment by ronnyBradston** [comment]
I'm having the same issue. Is there somebody who solved this?

**Comment by fishdood** [comment]
@hd8622, did you happen to get this information? My gut says it's in gmondpackets.rb, but I'm still fairly new to ruby.

**Comment by fishdood** [comment]
FYI, anyone having this issue, check the Pull requests. There are a couple solutions which work like a charm.

**Comment by suyograo** [comment]
Fixed in v3.1.0
