### ISSUE TITLE
can parse float type metric gen by gmetric command

### ISSUE THREAD

**Issue by kkpbbb** [logstash-plugins/logstash-input-ganglia#3]
Hi:

I gen custom metrics with gmetric command ,like 

gmetric -n 'test1' -v '10.1' -t float 

and I have modify ganglia.rb add  
event["val"] = data["val"]  

before line  %w{dmax tmax slope type units}.each do |info|

I can receive the custom metrics 'test1' from elasticsearch but the value is incorrect

it should be 10.1 but I got 5.605193857299268e-45

help me pls 

sorry for my bad english

**Comment by keybod** [comment]
Hi @kkpbbb. 
You could check my PR #5 if you are still on the problem.

**Comment by kkpbbb** [comment]
ok，thanks

I will try it

**Comment by suyograo** [comment]
Fixed in https://github.com/logstash-plugins/logstash-input-ganglia/pull/5
